# Generated by Django 6.1 on 2026-09-02 03:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'project analyses',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='intelligence.projectanalysis')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dependency_type', models.CharField(blank=True, default='', max_length=100)),
                ('inference_type', models.CharField(choices=[('EXPLICIT', 'Explicit'), ('INFERRED', 'Inferred')], default='EXPLICIT', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_out', to='intelligence.feature')),
                ('to_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_in', to='intelligence.feature')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='intelligence.projectanalysis')),
            ],
            options={
                'verbose_name_plural': 'dependencies',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('COVERED', 'Covered'), ('MISSING', 'Missing')], default='COVERED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='intelligence.projectanalysis')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='intelligence.feature')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='intelligence.projectanalysis')),
                ('requirement_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_a', to='intelligence.requirement')),
                ('requirement_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_b', to='intelligence.requirement')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='intelligence.projectanalysis')),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='intelligence.feature')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='intelligence.requirement')),
            ],
            options={
                'ordering': ['-severity', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_flows', to='intelligence.projectanalysis')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_flows', to='intelligence.feature')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SourceReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_references', to='intelligence.projectanalysis')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_references', to='documents.document')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='idx_source_ref_content_object')],
            },
        ),
        migrations.CreateModel(
            name='UserFlowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('actor', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='intelligence.userflow')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('user_flow', 'order'), name='unique_user_flow_step_order')],
            },
        ),
    ]
